### PR TITLE
Allow specifying --print-width in the CLI

### LINKED ISSUE #113: Make line width configurable on the CLI ?
We are evaluating this on discourse/discourse and all our plugins.

Things are looking good, but this jumped to me as weird:

https://github.com/discourse/discourse-chat/pull/1030/files#diff-001301097537175b30c546260016452d2ff11f02435e4acb6cbd4143d744b407R199

Is this because of line width? I see ternaries being removed in many places because of, I assume, line width. Can we get a cli option for line width? We have no immediate interest in forking nor using syntax_tree as a lib at the moment, so that would be great to help adoption.

### PR DESCRIPTION
**Pull request by kddnewton**
Fixes #113

### CODE REVIEW

**Comment by xfalcox** [comment]
I tried a similar approach last week, but that means that print-width is ignored for `stree lsp` right?

**Comment by kddnewton** [comment]
Ugh.. yes you're right. Pushing a fix momentarily.

**Comment by kddnewton** [comment]
@xfalcox it's out now in 3.2.0. Now the VSCode plugin needs to be updated to pass the argument in.

**Comment by xfalcox** [comment]
>  Now the VSCode plugin needs to be updated to pass the argument in.

Working on it!

**Pull request merged**
