### PR TITLE
Break and return false in forced_brace_bounds? when Parent is a Binary

### LINKED ISSUE #122: Block arguments in `if` statements uses `{`, triggering Rubocop
Sample code after formatting using `@prettier/plugin-ruby` 3:

```
    if current_user&.admin? ||
         Rails.application.config.x.team_ips.any? { |i|
           i.include?(request.remote_ip)
         }
      Rack::MiniProfiler.authorize_request
    end
```

This is triggering Rubocop, even after including this gem's config:

```
app/controllers/application_controller.rb:62:51: C: [Correctable] Style/BlockDelimiters: Avoid using {...} for multi-line blocks.
         Rails.application.config.x.team_ips.any? { |i|
```

The original code (formatted by the Prettier plugin v2) cas using `do … end`, which did not trigger Rubocop.

I am not sure what is the correct fix here:
- Format the code to use `do … end` again (but this might not be safe if I understand #120 correctly)
- Have the Rubocop config ignore this rule, as this gem will format it correctly

### PR DESCRIPTION
**Pull request by weizheheng**
Fixes #122

### CODE REVIEW

**Comment by weizheheng** [comment]
@kddnewton Sorry for opening another PR, [here](https://github.com/ruby-syntax-tree/syntax_tree/pull/143) is the original PR. I messed up the original PR while trying to fix the `idempotency_test`. Unfortunately, the tests are still failing and I appreciate it if you could give me some guidance on fixing it.

Tried running the `CI=true bundle exec rake` and it gave me more errors as compared to the Github Action run. The error I on Github Action run are:
- I am not sure why the `rdoc/parser/ruby.rb and c.rb` is raising syntax error.

CleanShot 2022-10-25 at 11 13 20@2x

**Comment by kddnewton** [comment]
No worries @weizheheng I'll take a look.

**Comment by kddnewton** [comment]
I did some more digging into this issue. The issue is this kind of expression:

```ruby
1 while line.gsub!(/\t+/) do
    ' ' * (tab_width*$&.length - $`.length % tab_width)
  end  && $~
```

In this case, it will get flipped into the non-modifier form, as in:

```ruby
while line.gsub!(/\t+/) do
        " " * (tab_width * $&.length - $`.length % tab_width)
      end && $~
  1
end
```

but with your PR it's going to use `do..end`. This means the `do` keyword is going to get confused with the optional `do` keyword of the `while` loop. Which means we need to do more than to just check if it's a `Binary` node.

**Comment by kddnewton** [comment]
I'm going to close this for now since it seems like we won't be able to solve this.

**Pull request closed without merging**
