### PR TITLE
Break and return false in forced_brace_bounds? when Parent is a Binary

### LINKED ISSUE #122: Block arguments in `if` statements uses `{`, triggering Rubocop
Sample code after formatting using `@prettier/plugin-ruby` 3:

```
    if current_user&.admin? ||
         Rails.application.config.x.team_ips.any? { |i|
           i.include?(request.remote_ip)
         }
      Rack::MiniProfiler.authorize_request
    end
```

This is triggering Rubocop, even after including this gem's config:

```
app/controllers/application_controller.rb:62:51: C: [Correctable] Style/BlockDelimiters: Avoid using {...} for multi-line blocks.
         Rails.application.config.x.team_ips.any? { |i|
```

The original code (formatted by the Prettier plugin v2) cas using `do … end`, which did not trigger Rubocop.

I am not sure what is the correct fix here:
- Format the code to use `do … end` again (but this might not be safe if I understand #120 correctly)
- Have the Rubocop config ignore this rule, as this gem will format it correctly

### PR DESCRIPTION
**Pull request by weizheheng**
Fixes #122 

Signed-off-by: Wei Zhe Heng <tech@weizheheng.com>

### CODE REVIEW

**Comment by weizheheng** [comment]
Thank you for this plugin, I am enjoying it with the Neovim integration so far. 

While going through the issue #122, it seems like the Binary node check should be added to `#forced_brace_bounds?` instead of `#unchangeable_bounds?`.

While adding a few tests, there is this test case that caught my attention:

## Actual Behavior
- Should the `barrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.any?` have the same indentation here?
```ruby
foo =
  barrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr if foooooooooooooooooooooo ||
  barrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.any? do |bar|
    bazzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
  end
```

## What I expected
- Extra indentation at the `barrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.any?`
```ruby
foo =
  barrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr if foooooooooooooooooooooo ||
    barrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.any? do |bar|
      bazzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
    end
```

**Comment by kddnewton** [comment]
Thank you so much for the pull request! This is very detailed in the tests, which I appreciate.

I think it should be

```ruby
if foooooooooooooooooooooo ||
     barrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.any? do |bar|
       bazzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
     end
  foo = barrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
end
```

at this point the modifier form of the `if` is too hard to read, so we should switch to multi-line.

**Comment by weizheheng** [comment]
@kddnewton Hi, yes of course, I'm on vacation now but will be back in three days. Will do it once I'm back.

**Comment by weizheheng** [comment]
@kddnewton Done rebasing. This PR is purely fixing #122.

Will probably look into the below in a different PR.

> Thank you so much for the pull request! This is very detailed in the tests, which I appreciate.
> 
> I think it should be
> 
> ```ruby
> if foooooooooooooooooooooo ||
>      barrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr.any? do |bar|
>        bazzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
>      end
>   foo = barrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
> end
> ```
> 
> at this point the modifier form of the `if` is too hard to read, so we should switch to multi-line.

**Comment by kddnewton** [comment]
Thank you!

**Comment by kddnewton** [comment]
@weizheheng looks like this failed CI on an idempotency check. You can check it locally with `CI=true bundle exec rake`. It checks the `.rb` files that ship with ruby itself.

**Pull request closed without merging**
